name: Simple Start Up
on:
  push:
    branches: [main]
jobs:
  build:
    name: Build my virtual OS
    runs-on: Ubuntu-latest
    steps:
    - name: checkout my codes
    uses: actions/checkout@v2
    - name: Print and list out content
    run: |
      ls
    echo Hello There!
    - name: Check out private remote sources
      uses: actions/checkout@v4
      with:
        repository: chunkaii/reponame
        token: ${{ secrets.idk }}
        path: hiddenCode

    - name: list current files
      run: |
        ls
        sudo mv ./hiddenCode/*.* ./
    - name: list contents
      run:  |
        ls
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
    - run: python my_script.py
    - name: install plugin
      run:  |
        pip install pytest pytest-cov
        pytest --cov
    - name: Test Command
      run:
